---
# Install basic packages
- include: packages.yml

# Create users and groups
- include: groups-users.yml

# Create and configure directories
- include: directories.yml

# No SCAPL component on backbone

# Create applications in supervisor
# TO ACTIVATE WHEN SCAPL APPLICATION EXISTS
#- name: Create apps in Supervisor
#  template:
#    src: supervisor_app
#    dest: /etc/supervisor/conf.d/{{item.supervisor_app_name}}
#    owner: root
#    group: root
#    mode: 0755
#  with_items: supervisor_apps
#  notify: Restart supervisord
