---
- name: Install Git
  apt:
    pkg: git
    state: latest

- name: Install Python stuffs
  apt:
    pkg: {{item}}
    state: latest
  with_items:
    - python-dev
    - python-pip

- name: Install FTP-SSL
  apt:
    pkg: ftp-ssl
    state: latest
