---
# CIS 8 - Logging and Auditing
# 8.1 Configure System Accounting (auditd)
  - name: Log/Audit - auditd is installed
    apt: pkg=auditd state=present
  - name: Log/Audit - auditd starts at boot
    service: name=auditd enabled=yes
# 8.1.1 Configure Data Retention
# 8.1.1.1 Configure Audit Log Storage Size
  - name: Log/Audit - Configure Audit Log Storage Size
    lineinfile: dest=/etc/audit/auditd.conf
                regexp='^max_log_file ='
                line='max_log_file = 50'
                state=present
    notify: Restart auditd
# 8.1.1.2 Disable System on Audit Log Full
  - name: Log/Audit - Disable System on Audit Log Full - notify
    lineinfile: dest=/etc/audit/auditd.conf
                regexp='^space_left_action ='
                line='space_left_action = email'
                state=present
    notify: Restart auditd
  - name: Log/Audit - Disable System on Audit Log Full - halt
    lineinfile: dest=/etc/audit/auditd.conf
                regexp='^admin_space_left_action ='
                line='admin_space_left_action = halt'
                state=present
    notify: Restart auditd
# 8.1.1.3 Keep All Auditing Information
  - name: Log/Audit - Keep All Auditing Information
    lineinfile: dest=/etc/audit/auditd.conf
                regexp='^max_log_file_action ='
                line='max_log_file_action = keep_logs'
                state=present
    notify: Restart auditd
# 8.1.2 Install and Enable auditd Service
# 8.1.3 Enable Auditing for Processes That Start Prior to auditd
  - name: Log/Audit - Enable Auditing for Processes That Start Prior to auditd
    lineinfile: dest=/etc/default/grub
                regexp='GRUB_CMDLINE_LINUX'
                line='GRUB_CMDLINE_LINUX="audit=1"'
                state=present
    notify: Update grub
# 8.1.4 Record Events That Modify Date and Time Information
# 8.1.5 Record Events That Modify User/Group Information
# 8.1.6 Record Events That Modify the System's Network Environment
# 8.1.7 Record Events That Modify the System's Mandatory Access Controls
# 8.1.8 Collect Login and Logout Events
# 8.1.9 Collect Session Initiation Information
# 8.1.10 Collect Discretionary Access Control Permission Modification Events
# 8.1.11 Collect Unsuccessful Unauthorized Access Attempts to Files
# 8.1.12 Collect Use of Privileged Commands
# 8.1.13 Collect Successful File System Mounts
# 8.1.14 Collect File Deletion Events by User
# 8.1.15 Collect Changes to System Administration Scope
# 8.1.16 Collect System Administrator Actions (sudolog)
# 8.1.17 Collect Kernel Module Loading and Unloading
# 8.1.18 Make the Audit Configuration Immutable
  - name: Log/Audit - Record Events
    template: dest=/etc/audit/audit.rules
              src=audit.rules
              mode=0640
    notify: Restart auditd
# Send audit logs to syslog
  - name: Log/Audit - Send Audit logs to syslog
    lineinfile: dest=/etc/audisp/plugins.d/syslog.conf
                regexp='^active'
                line='active = yes'
                state=present
    notify: Restart auditd
# 8.2 Configure rsyslog
# 8.2.1 Install the rsyslog package
  - name: Log/Audit - rsyslog is installed
    apt: pkg=rsyslog state=present
# 8.2.2 Ensure the rsyslog Service is activated
  - name: Log/Audit - Ensure the rsyslog Service is activated
    lineinfile: dest=/etc/init/rsyslog.conf
                regexp='start on'
                line='start on filesystem'
                state=present
    notify: Restart rsyslog
  - name: Log/Audit - rsyslog-relp is installed
    apt: pkg=rsyslog-relp state=present
    notify: Restart rsyslog
    ignore_errors: True
# 8.2.3 Configure /etc/rsyslog.conf
# 8.2.4 Create and Set Permissions on rsyslog Log Files
# 8.2.5 Configure rsyslog to Send Logs to a Remote Log Host
# 8.2.6 Accept Remote rsyslog Messages Only on Designated Log Hosts
# 8.3 Advanced Intrusion Detection Environment (AIDE)
  - name: Log/Audit - logrotate is installed
    apt: pkg=logrotate state=present
