---
# Specific process for the VmWare box
  - name: Remove box custom repo
    file: dest=/etc/apt/sources.list.d/puppetlabs.list
          state=absent

# Template task file, can include smaller files if warranted

# Locale
  - name: Configure Locale
    command: "{{ item }}"
    with_items:
    - dpkg-reconfigure locales
    - echo "LANG=\"en_US.UTF-8\"" > /etc/default/locale

# Keyboard layout
  - name: Configure keyboard layout
    lineinfile:
      dest: /etc/default/keyboard
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      state: present
      create: yes
    with_items:
      - { regexp: 'XKBMODEL=', line: 'XKBMODEL=\"pc105\"' }
      - { regexp: 'XKBLAYOUT=', line: 'XKBLAYOUT=\"be\"' }

# Apt
  - name: Update APT package cache
    apt: update_cache=yes
    
  - name: Upgrade APT to the lastest packages
    apt: upgrade=safe

# Global packages
  - name: Install baseline packages
    apt: pkg={{ item.package }}
         state=latest
    with_items: baseline_packages

# CIS Security Benchmarks for Ubuntu - Settings
#  source: http://cis-ubuntu-ansible.readthedocs.org/en/latest/CIS_Ubuntu/#cis-security-bencmarks-for-ubuntu
# CIS 1 - Patching and Software Updates
  - include: cis1.yml color=mauve
# CIS 2 - Filesystem Configuration
  - include: cis2.yml color=mauve
# CIS 3 - Secure Boot Settings
  - include: cis3.yml color=mauve
# CIS 4 - Additional Process Hardening
  - include: cis4.yml color=mauve
# CIS 5 - OS Services
  - include: cis5.yml color=mauve
# CIS 6 - Special Purpose Services
  - include: cis6.yml color=mauve
# CIS 7 - Network Configuration and Firewalls
  - include: cis7.yml color=mauve
# CIS 8 - Logging and Auditing
  - include: cis8.yml color=mauve
# 9 System Access, Authentication and Authorization
  - include: cis9.yml color=mauve
# 10 User Accounts and Environment
  - include: cis10.yml color=mauve
# 11 Warning Banners
  - include: cis11.yml color=mauve
# 12 Verify System File Permissions
  - include: cis12.yml color=mauve
# 13 Review User and Group Settings
  - include: cis13.yml color=mauve

# Other hardening
  - name: Authentication - sudo - forbit sudo su
    lineinfile: dest=/etc/sudoers
                regexp='Cmnd_Alias SUI=/bin/su'
                line='Cmnd_Alias SUI=/bin/su'
                state=present  
