---
# Install basic packages

- include: packages.yml

# Create users and groups

- include: groups-users.yml

# Create and configure directories

- include: directories.yml

# Clone the git repositories

- name: Clone repository
  git:
    repo: "https://github.com/dhondta/scapl-{{ scapl_component_name }}.git"
    dest: "{{ scapl_component_directory }}"
    force: yes
    recursive: no
    accept_hostkey: yes

# Install the requirements

- name: Install requirements
  pip:
    requirements: "{{ scapl_component_directory }}/requirements.txt"

# Create applications in supervisor
- name: Create apps in Supervisor
  template:
    src: supervisor_app
    dest: /etc/supervisor/conf.d/{{item.supervisor_app_name}}
    owner: root
    group: root
    mode: 0755
  with_items: supervisor_apps
  notify: Restart supervisord
