---
- name: Set huge pages on 400
  shell: sysctl vm.nr_hugepages=400

- name: Test if hugepages is already set on reboot
  shell: grep "^vm.nr_hugepages=400" /etc/sysctl.conf
  register: test_grep

- name: Add hugepages to the boot
  lineinfile: dest=/etc/sysctl.conf line="vm.nr_hugepages=400"
  when: test_grep.stdout != ""

- name: copy the postgres service script
  copy:
    src: ../files/postgresql.service
    dest: /etc/systemd/system/postgresql.service
    owner: frontend
    group: frontend
    mode: 0644



- name: Set PostgreSQL environment variables.
  template:
    src: postgres.sh.j2
    dest: /etc/profile.d/postgres.sh
    mode: 0644
  notify: restart postgresql

- name: Ensure PostgreSQL data directory exists.
  file:
    path: "{{ postgresql_data_dir }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    state: directory
    mode: 0700

- name: Check if PostgreSQL database is initialized.
  stat:
    path: "{{ postgresql_data_dir }}/PG_VERSION"
  register: pgdata_dir_version

- name: Ensure PostgreSQL database is initialized.
  command: "{{ postgresql_bin_path }}/initdb -D {{ postgresql_data_dir }}"
  when: not pgdata_dir_version.stat.exists
  become: true
  become_user: "{{ postgresql_user }}"
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true
