---
- hosts: scapl-automation
  sudo: True
  roles:
#    - baseline
    - supervisor
    - scapl-automation
  vars:
    # Global SCAPL-frontend configuration

    # python -c 'import crypt; print crypt.crypt("Password", "$1$SomeSalt$")'
    sysadmin_password: "$1$SomeSalt$scvwMFYVX0/NNuksR2vvw1"
    scapl_component_name: "automation"
    scapl_component_directory: "/opt/scapl/scapl-automation"
# TO ACTIVATE WHEN SCAPL APPLICATION EXISTS
#    supervisor_apps:
#      - supervisor_app_name: "automation_app"
#        supervisor_app_command: "celery worker -A automation.tasks:automation_app --hostname=automation_app.%%h --loglevel=INFO --without-gossip --without-mingle --without-heartbeat --soft-time-limit=60 --time-limit=300"
#        supervisor_app_user: "scapl"
