---
- hosts: scapl-frontend
  sudo: True
  roles:
    - baseline
    - postgresql
    - supervisor
    - apache
    - scapl-frontend
  vars:
    # Global SCAPL-frontend configuration

    # python -c 'import crypt; print crypt.crypt("back to the roots", "$1$SomeSalt$")'
    sysadmin_password: "$1$SomeSalt$LtUlD1y.JogMfbxzumljb1"
    scapl_component_name: "frontend"
    scapl_component_directory: "/opt/scapl/scapl-frontend"

    # MySQL configuration
    postgresql_port: "3306"
    postgresql_root_password: "scaplpassword"
    postgresql_users:
      - name: scapl
        host: localhost
        password: scaplpassword
        priv: "*.*:USAGE"
    postgresql_databases:
      - name: scapl
        collation: utf8_general_ci
        encoding: utf8
        replicate: 1
    ufw_rules:
      - { src: "{{ gateway }}", port: 8000 }
      - { src: "127.0.0.1", port: 5432 }
      - { src: "{{ backbone_server }}", port: "amqp" }

# TO ACTIVATE WHEN SCAPL APPLICATION EXISTS
    supervisor_apps:
      - supervisor_app_name: "frontend_app"
        supervisor_app_command: "celery worker -A frontend.tasks:frontend_app --hostname=frontend_app.%%h --loglevel=INFO --without-gossip --without-mingle --without-heartbeat --soft-time-limit=60 --time-limit=300"
        supervisor_app_user: "scapl"
