---
# Install basic packages

- name: Install packages
  apt:
    pkg: "{{item}}"
    state: latest
  with_items:
    - git
    - python-dev
    - python-pip
    - ftp-ssl

# Create users and groups

- include: groups-users.yml

# Create and configure directories

- include: directories.yml

# Clone the git repositories

- name: Clone repository
  git:
    repo: "https://github.com/dhondta/scapl-{{ scapl_component_name }}.git"
    dest: "{{ scapl_component_directory }}"
    force: yes
    recursive: no
    accept_hostkey: yes

# Install the requirements

- name: Install requirements
  pip:
    requirements: "{{ scapl_component_directory }}/requirements.txt"

# Create applications in supervisor
# TO ACTIVATE WHEN SCAPL APPLICATION EXISTS
#- name: Create apps in Supervisor
#  template:
#    src: supervisor_app
#    dest: /etc/supervisor/conf.d/{{item.supervisor_app_name}}
#    owner: root
#    group: root
#    mode: 0755
#  with_items: supervisor_apps
#  notify: Restart supervisord

- name: Copy configuration file of SCAPL-frontend
  template:
    src: frontend_config.ini
    dest: "{{ scapl_component_directory }}/config/"
    owner: sysadmin
