---
- name: Install Git
  apt:
    pkg: git
    state: latest

- name: Install Python stuffs
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - lib32z1-dev
    - libffi-dev
    - libxml2
    - libxslt1-dev
    - python3-dev
    - python3-pip
    - python-django
    - python-django-celery

- name: Install FTP-SSL
  apt:
    pkg: ftp-ssl
    state: latest

- name: Install GraphViz
  apt:
    pkg: graphviz
    state: latest
