---
# Clone the git repositories
- name: Clone repository
  git:
    repo: "https://github.com/dhondta/scapl-{{ scapl_component_name }}.git"
    dest: "{{ scapl_component_directory }}"
    force: yes
    recursive: no
    accept_hostkey: yes

# Install the requirements
- name: Install requirements
  pip:
    requirements: "{{ scapl_component_directory }}/requirements.txt"

# Copy configuration file
- name: Copy configuration file
  template:
    src: config.ini
    dest: "{{ scapl_component_directory }}/config/"
    owner: sysadmin
