---

- name: RabbitMQ | Install 
  apt: 
    pkg: "rabbitmq-server" 
    state: present
  notify: restart rabbitmq-server
  
- name: RabbitMQ | Enable rabbitmq-server to survive reboot
  service: 
    name: rabbitmq-server 
    enabled: yes

- name: RabbitMQ | Enable management plugin
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled
  notify: restart rabbitmq-server
  
- name: RabbitMQ | Create the ssl folder for rabbitmq
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items: 
    - /etc/rabbitmq/ssl/
    - /etc/rabbitmq/ssl/ca
    - /etc/rabbitmq/ssl/server
    - /etc/rabbitmq/ssl/client

- name: RabbitMQ | Generate the configuration of rabbitmq
  template:
    src: rabbitmq.config.j2
    dest: /etc/rabbitmq/rabbitmq.config
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: restart rabbitmq-server
 
- name: RabbitMQ | Add rabbitmq vhost
  rabbitmq_vhost: 
    name: "{{ item.name }}"
    state: present
  with_items: rabbitmq_vhost_definitions

- name: RabbitMQ | Add rabbitmq user and set priveleges
  rabbitmq_user:
    user: "{{ item.user }}"
    password: "{{ item.password }}"
    vhost: "{{ item.vhost }}"
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
    force: yes
  with_items: rabbitmq_users_definitions
  notify: restart rabbitmq-server
  
  
  
  
